### ISSUE TITLE
lua table

### ISSUE THREAD

**Issue by liangzyx** [lvzixun/sproto_dump#10]
请问下导出的lua table是有什么作用的

**Comment by lvzixun** [comment]
@spin6lock  我的这位同事加的， 他想知道协议定义的详细信息，从而在收到协议的时候做一些处理。

**Comment by spin6lock** [comment]
> 请问下导出的lua table是有什么作用的

sproto的字段都是optional的，有同事不希望协议发上来全部字段都校验一次有没有传，想做全字段必填，就搞了一份lua表，方便运行时做校验

**Comment by liangzyx** [comment]
好的，谢谢
